package com.myspace.dmnworkshop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer age;
	private int creditScore;
	private double monthlyIncome;
	private java.lang.String name;

	public Applicant() {
	}

	public int getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(int creditScore) {
		this.creditScore = creditScore;
	}

	public double getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(double monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public Applicant(java.lang.Integer age, int creditScore,
			double monthlyIncome, java.lang.String name) {
		this.age = age;
		this.creditScore = creditScore;
		this.monthlyIncome = monthlyIncome;
		this.name = name;
	}

}