package com.myspace.dmnworkshop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double amount;
	private java.lang.Integer duration;

	public Loan() {
	}

	public java.lang.Integer getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Integer duration) {
		this.duration = duration;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Loan(double amount, java.lang.Integer duration) {
		this.amount = amount;
		this.duration = duration;
	}

}